// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhotoBIZ.Api.Data;

#nullable disable

namespace PhotoBIZ.Api.Data.Migrations
{
    [DbContext(typeof(PhotoBizDbContext))]
    [Migration("20260509094741_InitialMvpDataFoundation")]
    partial class InitialMvpDataFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhotoBIZ.Api.Data.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedBoothId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_booth_id");

                    b.Property<Guid?>("ClientAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AssignedBoothId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_assigned_booth_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("ClientAccountId", "Role")
                        .HasDatabaseName("ix_users_client_account_id_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ClientAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.HasIndex("ClientAccountId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_client_account_id_created_at");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.Booth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentCredentialHash")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("agent_credential_hash");

                    b.Property<Guid>("ClientAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_account_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("current_state");

                    b.Property<string>("KioskTokenHash")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("kiosk_token_hash");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_booths");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_booths_location_id");

                    b.HasIndex("ClientAccountId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_booths_client_account_id_code");

                    b.HasIndex("ClientAccountId", "CurrentState")
                        .HasDatabaseName("ix_booths_client_account_id_current_state");

                    b.HasIndex("ClientAccountId", "Status")
                        .HasDatabaseName("ix_booths_client_account_id_status");

                    b.ToTable("booths", (string)null);
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.BoothPackage", b =>
                {
                    b.Property<Guid>("BoothId")
                        .HasColumnType("uuid")
                        .HasColumnName("booth_id");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.HasKey("BoothId", "PackageId")
                        .HasName("pk_booth_packages");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("ix_booth_packages_package_id");

                    b.ToTable("booth_packages", (string)null);
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.BoothSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedPackageIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("assigned_package_ids");

                    b.Property<Guid>("BoothId")
                        .HasColumnType("uuid")
                        .HasColumnName("booth_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("LumaboothSessionRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lumabooth_session_ref");

                    b.Property<string>("SessionLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("session_label");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<string>("WelcomeHeadline")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("welcome_headline");

                    b.Property<string>("WelcomeSubtitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("welcome_subtitle");

                    b.HasKey("Id")
                        .HasName("pk_booth_sessions");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_booth_sessions_transaction_id");

                    b.HasIndex("BoothId", "Status")
                        .HasDatabaseName("ix_booth_sessions_booth_id_status");

                    b.ToTable("booth_sessions", (string)null);
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.BoothTerminalConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoothId")
                        .HasColumnType("uuid")
                        .HasColumnName("booth_id");

                    b.Property<string>("ComPort")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("com_port");

                    b.Property<DateTimeOffset?>("LastConnectionTestAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_connection_test_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider");

                    b.Property<string>("SerialOrAssetTag")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("serial_or_asset_tag");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("TerminalModel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("terminal_model");

                    b.Property<string>("TerminalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("terminal_reference");

                    b.HasKey("Id")
                        .HasName("pk_booth_terminal_configs");

                    b.HasIndex("BoothId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ix_booth_terminal_configs_booth_id_provider");

                    b.ToTable("booth_terminal_configs", (string)null);
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.ClientAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_client_accounts");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_client_accounts_name");

                    b.ToTable("client_accounts", (string)null);
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.ClientBoothTheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("accent_color");

                    b.Property<string>("BackgroundImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("background_image_url");

                    b.Property<Guid>("ClientAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_account_id");

                    b.Property<string>("DefaultWelcomeHeadline")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("default_welcome_headline");

                    b.Property<string>("DefaultWelcomeSubtitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_welcome_subtitle");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("logo_url");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("primary_color");

                    b.Property<string>("ThemePreset")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("theme_preset");

                    b.HasKey("Id")
                        .HasName("pk_client_booth_themes");

                    b.HasIndex("ClientAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_client_booth_themes_client_account_id");

                    b.ToTable("client_booth_themes", (string)null);
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.ClientPaymentProviderConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessAccountName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("business_account_name");

                    b.Property<Guid>("ClientAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_account_id");

                    b.Property<string>("EncryptedSecretKey")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("encrypted_secret_key");

                    b.Property<string>("IntegrationType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("integration_type");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider");

                    b.Property<string>("PublicKeyMasked")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("public_key_masked");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("webhook_url");

                    b.HasKey("Id")
                        .HasName("pk_client_payment_provider_configs");

                    b.HasIndex("ClientAccountId", "Provider", "IntegrationType")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_configs_client_provider_type");

                    b.ToTable("client_payment_provider_configs", (string)null);
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.ClientSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActiveBoothAllowance")
                        .HasColumnType("integer")
                        .HasColumnName("active_booth_allowance");

                    b.Property<Guid>("ClientAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_account_id");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_plan_id");

                    b.HasKey("Id")
                        .HasName("pk_client_subscriptions");

                    b.HasIndex("SubscriptionPlanId")
                        .HasDatabaseName("ix_client_subscriptions_subscription_plan_id");

                    b.HasIndex("ClientAccountId", "Status")
                        .HasDatabaseName("ix_client_subscriptions_client_account_id_status");

                    b.ToTable("client_subscriptions", (string)null);
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<Guid>("ClientAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_account_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("ClientAccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_locations_client_account_id_name");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid>("ClientAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_account_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("LumaboothPresetRef")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lumabooth_preset_ref");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PaperSize")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("paper_size");

                    b.Property<int>("PriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("price_cents");

                    b.Property<int>("PrintCount")
                        .HasColumnType("integer")
                        .HasColumnName("print_count");

                    b.HasKey("Id")
                        .HasName("pk_packages");

                    b.HasIndex("ClientAccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_packages_client_account_id_name");

                    b.ToTable("packages", (string)null);
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.PaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_reference");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_payment_attempts");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_payment_attempts_transaction_id");

                    b.HasIndex("Provider", "ProviderReference")
                        .HasDatabaseName("ix_payment_attempts_provider_provider_reference");

                    b.ToTable("payment_attempts", (string)null);
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("PricePerBoothCents")
                        .HasColumnType("integer")
                        .HasColumnName("price_per_booth_cents");

                    b.HasKey("Id")
                        .HasName("pk_subscription_plans");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_subscription_plans_name");

                    b.ToTable("subscription_plans", (string)null);
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AmountCents")
                        .HasColumnType("integer")
                        .HasColumnName("amount_cents");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<Guid>("BoothId")
                        .HasColumnType("uuid")
                        .HasColumnName("booth_id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid>("ClientAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_account_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<string>("PackageSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("package_snapshot");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("transaction_number");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("ApprovedByUserId")
                        .HasDatabaseName("ix_transactions_approved_by_user_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_transactions_expires_at");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_transactions_location_id");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("ix_transactions_package_id");

                    b.HasIndex("TransactionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_transaction_number");

                    b.HasIndex("BoothId", "Status")
                        .HasDatabaseName("ix_transactions_booth_id_status");

                    b.HasIndex("ClientAccountId", "Status")
                        .HasDatabaseName("ix_transactions_client_account_id_status");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.ApplicationUser", b =>
                {
                    b.HasOne("PhotoBIZ.Api.Data.Booth", "AssignedBooth")
                        .WithOne("AssignedCashier")
                        .HasForeignKey("PhotoBIZ.Api.Data.ApplicationUser", "AssignedBoothId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_booths_assigned_booth_id");

                    b.HasOne("PhotoBIZ.Api.Data.ClientAccount", "ClientAccount")
                        .WithMany("Users")
                        .HasForeignKey("ClientAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_client_accounts_client_account_id");

                    b.Navigation("AssignedBooth");

                    b.Navigation("ClientAccount");
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.AuditLog", b =>
                {
                    b.HasOne("PhotoBIZ.Api.Data.ClientAccount", "ClientAccount")
                        .WithMany()
                        .HasForeignKey("ClientAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_logs_client_accounts_client_account_id");

                    b.HasOne("PhotoBIZ.Api.Data.ApplicationUser", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_logs_users_user_id");

                    b.Navigation("ClientAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.Booth", b =>
                {
                    b.HasOne("PhotoBIZ.Api.Data.ClientAccount", "ClientAccount")
                        .WithMany()
                        .HasForeignKey("ClientAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booths_client_accounts_client_account_id");

                    b.HasOne("PhotoBIZ.Api.Data.Location", "Location")
                        .WithMany("Booths")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booths_locations_location_id");

                    b.Navigation("ClientAccount");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.BoothPackage", b =>
                {
                    b.HasOne("PhotoBIZ.Api.Data.Booth", "Booth")
                        .WithMany("BoothPackages")
                        .HasForeignKey("BoothId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booth_packages_booths_booth_id");

                    b.HasOne("PhotoBIZ.Api.Data.Package", "Package")
                        .WithMany("BoothPackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booth_packages_packages_package_id");

                    b.Navigation("Booth");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.BoothSession", b =>
                {
                    b.HasOne("PhotoBIZ.Api.Data.Booth", "Booth")
                        .WithMany("BoothSessions")
                        .HasForeignKey("BoothId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booth_sessions_booths_booth_id");

                    b.HasOne("PhotoBIZ.Api.Data.Transaction", "Transaction")
                        .WithMany("BoothSessions")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booth_sessions_transactions_transaction_id");

                    b.Navigation("Booth");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.BoothTerminalConfig", b =>
                {
                    b.HasOne("PhotoBIZ.Api.Data.Booth", "Booth")
                        .WithMany("TerminalConfigs")
                        .HasForeignKey("BoothId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booth_terminal_configs_booths_booth_id");

                    b.Navigation("Booth");
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.ClientBoothTheme", b =>
                {
                    b.HasOne("PhotoBIZ.Api.Data.ClientAccount", "ClientAccount")
                        .WithOne("BoothTheme")
                        .HasForeignKey("PhotoBIZ.Api.Data.ClientBoothTheme", "ClientAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_client_booth_themes_client_accounts_client_account_id");

                    b.Navigation("ClientAccount");
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.ClientPaymentProviderConfig", b =>
                {
                    b.HasOne("PhotoBIZ.Api.Data.ClientAccount", "ClientAccount")
                        .WithMany("PaymentProviderConfigs")
                        .HasForeignKey("ClientAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_configs_client_account");

                    b.Navigation("ClientAccount");
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.ClientSubscription", b =>
                {
                    b.HasOne("PhotoBIZ.Api.Data.ClientAccount", "ClientAccount")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ClientAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_client_subscriptions_client_accounts_client_account_id");

                    b.HasOne("PhotoBIZ.Api.Data.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("ClientSubscriptions")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_client_subscriptions_subscription_plans_subscription_plan_id");

                    b.Navigation("ClientAccount");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.Location", b =>
                {
                    b.HasOne("PhotoBIZ.Api.Data.ClientAccount", "ClientAccount")
                        .WithMany("Locations")
                        .HasForeignKey("ClientAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_locations_client_accounts_client_account_id");

                    b.Navigation("ClientAccount");
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.Package", b =>
                {
                    b.HasOne("PhotoBIZ.Api.Data.ClientAccount", "ClientAccount")
                        .WithMany("Packages")
                        .HasForeignKey("ClientAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_packages_client_accounts_client_account_id");

                    b.Navigation("ClientAccount");
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.PaymentAttempt", b =>
                {
                    b.HasOne("PhotoBIZ.Api.Data.Transaction", "Transaction")
                        .WithMany("PaymentAttempts")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_attempts_transactions_transaction_id");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.Transaction", b =>
                {
                    b.HasOne("PhotoBIZ.Api.Data.ApplicationUser", "ApprovedByUser")
                        .WithMany("ApprovedTransactions")
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_users_approved_by_user_id");

                    b.HasOne("PhotoBIZ.Api.Data.Booth", "Booth")
                        .WithMany("Transactions")
                        .HasForeignKey("BoothId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_booths_booth_id");

                    b.HasOne("PhotoBIZ.Api.Data.ClientAccount", "ClientAccount")
                        .WithMany()
                        .HasForeignKey("ClientAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_client_accounts_client_account_id");

                    b.HasOne("PhotoBIZ.Api.Data.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_locations_location_id");

                    b.HasOne("PhotoBIZ.Api.Data.Package", "Package")
                        .WithMany("Transactions")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_packages_package_id");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Booth");

                    b.Navigation("ClientAccount");

                    b.Navigation("Location");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.ApplicationUser", b =>
                {
                    b.Navigation("ApprovedTransactions");

                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.Booth", b =>
                {
                    b.Navigation("AssignedCashier");

                    b.Navigation("BoothPackages");

                    b.Navigation("BoothSessions");

                    b.Navigation("TerminalConfigs");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.ClientAccount", b =>
                {
                    b.Navigation("BoothTheme");

                    b.Navigation("Locations");

                    b.Navigation("Packages");

                    b.Navigation("PaymentProviderConfigs");

                    b.Navigation("Subscriptions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.Location", b =>
                {
                    b.Navigation("Booths");
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.Package", b =>
                {
                    b.Navigation("BoothPackages");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.SubscriptionPlan", b =>
                {
                    b.Navigation("ClientSubscriptions");
                });

            modelBuilder.Entity("PhotoBIZ.Api.Data.Transaction", b =>
                {
                    b.Navigation("BoothSessions");

                    b.Navigation("PaymentAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
